# Based on .travis.yml in `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)

sudo: true

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
    - REPO_PATH="$TRAVIS_REPO_SLUG"
    - RELEASE_NAME="$TRAVIS_BRANCH-autobuild"
    - TAG_NAME="$TRAVIS_BRANCH-autobuild-tag"
    
matrix:
  allow_failures:
    - os: osx
  include:
    #- os: osx
    #  env: LAZ_VER=1.4.4
    - os: linux
      env: LAZ_VER=1.8.2
      if: tag IS blank
    #- os: linux
    #  env: LAZ_VER=1.4.4 LAZ_WINE=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    #- os: linux
    #env: LAZ_VER=1.4.4 LAZ_WINE=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
  # Install environment prerequisites
  - sudo apt-get update && sudo apt-get install xvfb python-sphinx graphviz libxtst-dev libkeybinder-dev || true
  - Xvfb $DISPLAY &

install:
  # Install testing prerequisites (wine/fpc/lazarus)
  - ./autobuild/travis-lazarus/.travis.install.py

script:
  # Generate Simba.exe in debug and release mode
  #- $LAZ_WINE lazbuild --bm=debug   $LAZ_OPT ./Projects/Simba/Simba.lpi
  - $LAZ_WINE lazbuild --bm=release $LAZ_OPT ./Projects/Simba/Simba.lpi
  
before_deploy:
  # Delete previous release (no output just to be safe)
  - python ./autobuild/travis-delete-release.py | tee >/dev/null
  
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file:
    - "Simba.x86_64-linux"
    - "Simba.i386-win32.exe"
  name: $RELEASE_NAME
  tag_name: $TAG_NAME
  prerelease: true
  body: "Automatic development build of the $TRAVIS_BRANCH branch."
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST == "false"

#notifications:
#  email: false
#  irc:
#    channels: "irc.rizon.net#simba"
#    template:
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#    on_success: always
#    on_failure: always
#    use_notice: true
#    skip_join: true
